set nocompatible
filetype on
filetype indent on
filetype plugin on
filetype plugin indent on
set autoindent

set t_Co=256
set encoding=utf-8
set hidden
set autoread
set autochdir
"set mouse=a

syntax on

set number
set relativenumber
set wrap
set showcmd
set wildmenu
set cursorline
set laststatus=2
set scrolloff=5
"set spell

set list
set listchars=tab:▸\ ,trail:▫
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set matchpairs+=<:>
set backspace=indent,eol,start
"set clipboard=unnamed

au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

"search
set hlsearch
set incsearch
set ignorecase
set smartcase
exec "nohlsearch"
"noremap J :noh<cr><esc>

"imap vk to <Esc>
inoremap vk <Esc>
inoremap vv <C-o>

nnoremap v <C-v>
nnoremap <C-v> v
vnoremap v <C-v>
vnoremap <C-v> v

"Colemak
"map n h <Left>
"map e j <Down>
"map u k <Up>
"map i l <Right>
noremap n h
noremap e j
noremap u k
noremap i l
noremap E 5j
noremap U 5k
noremap N ^
noremap I $

"Remap HJKL
"map h i insert
"map j e end of word
"map k n next/previous
"map l u undo/redo
noremap j e
noremap l u
noremap L <C-r>
noremap h i
noremap H I
nnoremap k nzz
nnoremap K Nzz
vnoremap k <Esc>:noh<CR><Esc>
vnoremap K <Esc>

"break the undo blocks
inoremap <C-u> <C-g>u<C-u>
inoremap <C-w> <C-g>u<C-w>

"use tabs to intend
nnoremap <Tab> >>_
nnoremap <S-Tab> <<_
vnoremap <Tab> >gv
vnoremap <S-Tab> <gv

let mapleader=" "
"Key bindings
"a [ide-a] stop
"b
"c [ide-c] run class
"d [ide-d] debug
"e [vim-e] move to window down
"f [vim-f] move to char [ide-f] move to file
"g
"h [vim-h] split screen horizontally
"i [vim-i] move to window right
"j
"k [ide-k] refactor code
"l [vim-l] move to line [ide-l] move to line
"m [all-m] delete mark
"n [vim-n] move to window left
"o [ide-o] open terminal
"p [all-p] paste clipboard
"q [all-q] record macro
"r [vim-r] resize screen
"s [all-s] split screen
"t [ide-t] move to terminal
"u [vim-u] move to window up
"v [vim-v] split screen vertically
"w [vim-w] move to word [ide-w] move to word
"x [ide-x] run
"y [all-y] copy clipboard
"z [ide-z] comment/uncomment code

"system clipboard copy/paste
noremap <leader>y "*y
noremap <leader>p "*p
noremap <leader>Y "+y
noremap <leader>P "+p

"curser switch
noremap <leader>n <C-w>h
noremap <leader>e <C-w>j
noremap <leader>u <C-w>k
noremap <leader>i <C-w>l

"split screen
noremap <leader>sn :set nosplitright<CR>:vsplit<CR>
noremap <leader>se :set splitbelow<CR>:split<CR>
noremap <leader>su :set nosplitbelow<CR>:split<CR>
noremap <leader>si :set splitright<CR>:vsplit<CR>

"screen resize
noremap <leader>rn :vertical resize-5<CR>
noremap <leader>re :res -5<CR>
noremap <leader>ru :res +5<CR>
noremap <leader>ri :vertical resize+5<CR>

"rearrange screen
noremap <leader>v <C-w>t<C-w>H
noremap <leader>h <C-w>t<C-w>K

"use t for shortcuts
"Key bindings
"a [vim-a] search file [ide-a] search action
"b [all-b] jump back
"c
"d
"e
"f [ide-f] search global
"g
"h [all-h] jump to line start
"i [vim-i] next tab [ide-i] next tab
"j [all-j] toggle spell check
"k
"l [all-l] toggle line number
"m [all-m] jump to modified line
"n [vim-n] prev tab [ide-n] prev tab
"o [all-o] jump to pair bracket
"p
"q [all-q] replay macro
"r [ide-r] recent files
"s [all-S] save [vim-s] search file [ide-s] search everywhere
"t [vim-T] quit [vim-t] toggle NERDTree [ide-t] toggle file tree [ide-T] close tab
"u [vim-u] new tab
"v [vim-v] reload vimrc [ide-v] reload ideavimrc
"w
"x
"y
"z

nnoremap tc <nop>
nnoremap td <nop>
nnoremap te <nop>
nnoremap tf <nop>
nnoremap tg <nop>
nnoremap tk <nop>
nnoremap tp <nop>
nnoremap tr <nop>
nnoremap tx <nop>
nnoremap ty <nop>
nnoremap tz <nop>

"manage tabs
nnoremap tu :tabe<CR>
nnoremap tn :-tabnext<CR>
nnoremap ti :+tabnext<CR>

"mark jump
nnoremap tm `
nnoremap tb ``
nnoremap th 0
nnoremap to %

"macros
nnoremap <leader>q qzqqz
nnoremap tq @z

"spell check
nnoremap tj :set spell!<CR>

" line number format
nnoremap tl :set relativenumber!<CR>

"reload vimrc
nnoremap tv :source $MYVIMRC<CR>

"map S save
"map T quit
nnoremap S :write<CR>
nnoremap T :quit<CR>

"use only capital letters for marks
"idea marks only support upper cases
nnoremap ma mA
nnoremap mb mB
nnoremap mc mC
nnoremap md mD
nnoremap me mE
nnoremap mf mF
nnoremap mg mG
nnoremap mh mH
nnoremap mi mI
nnoremap mj mJ
nnoremap mk mK
nnoremap ml mL
nnoremap mm mM
nnoremap mn mN
nnoremap mo mO
nnoremap mp mP
nnoremap mq mQ
nnoremap mr mR
nnoremap ms mS
nnoremap mt mT
nnoremap mu mU
nnoremap mv mV
nnoremap mw mW
nnoremap mx mX
nnoremap my mY
nnoremap mz mZ

nnoremap 'a 'A
nnoremap 'b 'B
nnoremap 'c 'C
nnoremap 'd 'D
nnoremap 'e 'E
nnoremap 'f 'F
nnoremap 'g 'G
nnoremap 'h 'H
nnoremap 'i 'I
nnoremap 'j 'J
nnoremap 'k 'K
nnoremap 'l 'L
nnoremap 'm 'M
nnoremap 'n 'N
nnoremap 'o 'O
nnoremap 'p 'P
nnoremap 'q 'Q
nnoremap 'r 'R
nnoremap 's 'S
nnoremap 't 'T
nnoremap 'u 'U
nnoremap 'v 'V
nnoremap 'w 'W
nnoremap 'x 'X
nnoremap 'y 'Y
nnoremap 'z 'Z

nnoremap <Leader>ma :delmark A<CR>
nnoremap <Leader>mb :delmark B<CR>
nnoremap <Leader>mc :delmark C<CR>
nnoremap <Leader>md :delmark D<CR>
nnoremap <Leader>me :delmark E<CR>
nnoremap <Leader>mf :delmark F<CR>
nnoremap <Leader>mg :delmark G<CR>
nnoremap <Leader>mh :delmark H<CR>
nnoremap <Leader>mi :delmark I<CR>
nnoremap <Leader>mj :delmark J<CR>
nnoremap <Leader>mk :delmark K<CR>
nnoremap <Leader>ml :delmark L<CR>
nnoremap <Leader>mm :delmark M<CR>
nnoremap <Leader>mn :delmark N<CR>
nnoremap <Leader>mo :delmark O<CR>
nnoremap <Leader>mp :delmark P<CR>
nnoremap <Leader>mq :delmark Q<CR>
nnoremap <Leader>mr :delmark R<CR>
nnoremap <Leader>ms :delmark S<CR>
nnoremap <Leader>mt :delmark T<CR>
nnoremap <Leader>mu :delmark U<CR>
nnoremap <Leader>mv :delmark V<CR>
nnoremap <Leader>mw :delmark W<CR>
nnoremap <Leader>mx :delmark X<CR>
nnoremap <Leader>my :delmark Y<CR>
nnoremap <Leader>mz :delmark Z<CR>

nnoremap <Leader>mA :delmark A<CR>
nnoremap <Leader>mB :delmark B<CR>
nnoremap <Leader>mC :delmark C<CR>
nnoremap <Leader>mD :delmark D<CR>
nnoremap <Leader>mE :delmark E<CR>
nnoremap <Leader>mF :delmark F<CR>
nnoremap <Leader>mG :delmark G<CR>
nnoremap <Leader>mH :delmark H<CR>
nnoremap <Leader>mI :delmark I<CR>
nnoremap <Leader>mJ :delmark J<CR>
nnoremap <Leader>mK :delmark K<CR>
nnoremap <Leader>mL :delmark L<CR>
nnoremap <Leader>mM :delmark M<CR>
nnoremap <Leader>mN :delmark N<CR>
nnoremap <Leader>mO :delmark O<CR>
nnoremap <Leader>mP :delmark P<CR>
nnoremap <Leader>mQ :delmark Q<CR>
nnoremap <Leader>mR :delmark R<CR>
nnoremap <Leader>mS :delmark S<CR>
nnoremap <Leader>mT :delmark T<CR>
nnoremap <Leader>mU :delmark U<CR>
nnoremap <Leader>mV :delmark V<CR>
nnoremap <Leader>mW :delmark W<CR>
nnoremap <Leader>mX :delmark X<CR>
nnoremap <Leader>mY :delmark Y<CR>
nnoremap <Leader>mZ :delmark Z<CR>
