set nocompatible
filetype on
filetype indent on
filetype plugin on
filetype plugin indent on
set autoindent

set t_Co=256
set encoding=utf-8
set hidden
set autoread
set autochdir
"set mouse=a

syntax on

set number
set relativenumber
set wrap
set showcmd
set wildmenu
set cursorline
set laststatus=2
set scrolloff=5
"set spell

set list
set listchars=tab:▸\ ,trail:▫
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set matchpairs+=<:>
set backspace=indent,eol,start

au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

"search
set hlsearch
set incsearch
set ignorecase
set smartcase
exec "nohlsearch"
"noremap J :noh<cr><esc>

"imap vk to <Esc>
inoremap vk <Esc>

"Colemak
"map n h <Left>
"map e j <Down>
"map u k <Up>
"map i l <Right>
noremap n h
noremap e j
noremap u k
noremap i l
noremap E 5j
noremap U 5k
noremap N 0
noremap I $

"Remap HJKL
"map h i insert
"map j e end of word
"map k n next/previous
"map l u undo/redo
noremap j e
noremap l u
noremap L <C-r>
noremap h i
noremap H I
nnoremap k nzz
nnoremap K Nzz
vnoremap k <Esc>:noh<CR><Esc>
vnoremap K <Esc>

let mapleader=" "
"unused ops:
"a  d .g  jk.m
" o q  t  .x z

"ender visual-block mode
noremap <leader>b <C-v>

"system clipboard copy/paste
noremap <Leader>y "*y
noremap <Leader>p "*p
noremap <Leader>Y "+y
noremap <Leader>P "+p

"split screen
map <leader>n :set nosplitright<CR>:vsplit<CR>
map <leader>e :set splitbelow<CR>:split<CR>
map <leader>u :set nosplitbelow<CR>:split<CR>
map <leader>i :set splitright<CR>:vsplit<CR>

"curser switch
map <leader>sn <C-w>h
map <leader>se <C-w>j
map <leader>su <C-w>k
map <leader>si <C-w>l

"screen resize
map <leader>rn :vertical resize-5<CR>
map <leader>re :res -5<CR>
map <leader>ru :res +5<CR>
map <leader>ri :vertical resize+5<CR>

"rearrange screen
map <leader>v <C-w>t<C-w>H
map <leader>h <C-w>t<C-w>K

"use t for shortcuts
noremap t <nop>
"unused ops:
". cdefgh  k  
" opqr.. vwxyz

"manage tabs
map tu :tabe<CR>
map tn :-tabnext<CR>
map ti :+tabnext<CR>

"mark jump
map tm `
map tb ``
map to %

"spell ckeck
noremap tl :set spell!<CR>

" line number format
noremap tj :set relativenumber!<CR>

"bring back some useful combinations
nnoremap dt dt
nnoremap ct ct

"map S save
"map T quit
nmap S :write<CR>
nmap T :quit<CR>

"reload vimrc
noremap <leader>c :source $MYVIMRC<CR>

