[appearance]

[appearance.text]
notebook_font_size = 14.0
font_size = 13.5
font_name = "CommitMonoCode Nerd Font"
line_height_ratio = 1.2
ai_font_name = "CommitMonoCode Nerd Font"
match_ai_font = true
ligature_rendering_enabled = true

[appearance.themes]
system_theme = false
theme = { custom = { name = "Jellybeans", path = "~/.warp/themes/standard/jellybeans.yaml" } }

[appearance.vertical_tabs]
view_mode = "expanded"
display_granularity = "panes"
compact_subtitle = "branch"
primary_info = "command"
show_pr_link = true
enabled = true

[appearance.icon]
app_icon = "warp_one"

[appearance.window]
override_blur = 55
override_opacity = 77

[appearance.panes]
should_dim_inactive_panes = true
focus_pane_on_hover = true

[appearance.tabs]
show_indicators_button = true
workspace_decoration_visibility = "hide_fullscreen"

[terminal]
maximum_grid_size = 100000

[terminal.input]
input_box_type_setting = "universal"
honor_ps1 = false

[agents]
cloud_conversation_storage_enabled = true

[agents.warp_agent]

[agents.warp_agent.input]
nld_in_terminal_enabled = true

[agents.third_party]
auto_open_composer_on_cli_agent_start = false
auto_dismiss_composer_after_submit = false

[agents.third_party.cli_agent_toolbar_enabled_commands]

[notifications]
toast_duration_secs = 8

[notifications.preferences]
is_agent_task_completed_enabled = true
is_long_running_enabled = true
is_needs_attention_enabled = true
is_password_prompt_enabled = true
long_running_threshold = 30
mode = "enabled"
play_notification_sound = true

[account]
is_settings_sync_enabled = true

[privacy]
crash_reporting_enabled = false
telemetry_enabled = false

[code]

[code.editor]
open_file_editor = { external_editor = "vs_code" }

[keys]
ctrl_tab_behavior_setting = "cycle_most_recent_session"
